replicaCount: 1

image:
  repository: 279867549867.dkr.ecr.us-east-1.amazonaws.com/blostemiq-outreach
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8003

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  PORT: "8003"
  LOG_LEVEL: INFO

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

probe:
  path: /health
  port: 8003
