replicaCount: 1

image:
  repository: 279867549867.dkr.ecr.us-east-1.amazonaws.com/blostemiq-billing-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 3005

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  NODE_ENV: production
  PORT: "3005"
  BILLING_SUCCESS_URL: "https://app.blostemiq.com/dashboard/settings"
  BILLING_CANCEL_URL: "https://app.blostemiq.com/dashboard/settings"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

probe:
  path: /health
  port: 3005
