replicaCount: 2

image:
  repository: 279867549867.dkr.ecr.us-east-1.amazonaws.com/blostemiq-notification-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 3004

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

env:
  NODE_ENV: production
  PORT: "3004"
  LOG_LEVEL: info
  AWS_REGION: us-east-1
  ALLOWED_ORIGINS: "http://blostemiq.ddns.net,https://blostemiq.ddns.net,http://localhost:3000"
  REDIS_URL: "redis://blostemiq-dev-redis.t6n5iw.0001.use1.cache.amazonaws.com:6379"
  KAFKA_BROKERS: "localhost:9092"


hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

probe:
  path: /health
  port: 3004
