replicaCount: 1

image:
  repository: 279867549867.dkr.ecr.us-east-1.amazonaws.com/blostemiq-lead-scoring
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8002

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 2000m
    memory: 2Gi

env:
  PORT: "8002"
  LOG_LEVEL: INFO

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

probe:
  path: /health
  port: 8002
