replicaCount: 2

image:
  repository: 279867549867.dkr.ecr.us-east-1.amazonaws.com/blostemiq-auth-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 3001

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  NODE_ENV: production
  PORT: "3001"
  LOG_LEVEL: info
  AWS_REGION: us-east-1
  DATABASE_URL: "postgresql://blostemiq:CQASqiCU8cn3AU4HwjuxOcMSNI5ht8EN@blostemiq-dev.culc24yc0frz.us-east-1.rds.amazonaws.com:5432/blostemiq?schema=auth"
  REDIS_URL: "redis://blostemiq-dev-redis.t6n5iw.0001.use1.cache.amazonaws.com:6379"


hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

probe:
  path: /health
  port: 3001
